# Generated by Django 5.0.2 on 2024-03-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('online', 'online'), ('offline', 'offline')], max_length=8),
        ),
    ]
