# Generated by Django 5.0.2 on 2024-03-05 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_room_id_room_room_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='sender',
            new_name='user1',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='reciever',
            new_name='user2',
        ),
    ]
